server {
    listen 80;
    server_name easynodeone.com www.easynodeone.com;
    root /var/www/easynodeone;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
    location /logos/ {
        alias /var/www/easynodeone/logos/;
    }
    location /assets/ {
        alias /var/www/easynodeone/assets/;
    }
}
