"""Constantes sync offline — Etapa 13."""

from __future__ import annotations

SYNC_DOMAIN_EVENTS = 'events'
SYNC_DOMAIN_CATALOG = 'catalog'
SYNC_DOMAIN_ORDERS = 'orders'

SYNC_DOMAINS = frozenset({SYNC_DOMAIN_EVENTS, SYNC_DOMAIN_CATALOG, SYNC_DOMAIN_ORDERS})

CONFLICT_STRATEGY_SERVER_WINS = 'server_wins'
CONFLICT_STRATEGY_CLIENT_WINS = 'client_wins'
CONFLICT_STRATEGY_MANUAL = 'manual'

CONFLICT_STRATEGIES = frozenset(
    {CONFLICT_STRATEGY_SERVER_WINS, CONFLICT_STRATEGY_CLIENT_WINS, CONFLICT_STRATEGY_MANUAL}
)

DEFAULT_MAX_RETRIES = 5
DEFAULT_BASE_RETRY_SECONDS = 30
