"""EPosOne V4 — dominio portable + puertos de datos (Sprint 3).

El dominio nunca conoce SQLite ni EN1. Los providers viven en
``memory``, ``sqlite`` y ``api``.
"""

from nodeone.core.eposone_domain.models import (
    Address,
    Branch,
    BusinessConfig,
    CashShift,
    Customer,
    Device,
    Employee,
    InventoryBalance,
    KitLine,
    Order,
    OrderLine,
    Payment,
    Product,
    Promotion,
    Register,
    TaxRate,
)
from nodeone.core.eposone_domain.first_start import (
    FIRST_START_CHOICES,
    LABEL_CONNECT_EN1,
    LABEL_CREATE_BUSINESS,
    ConnectEn1Input,
    CreateBusinessInput,
    FirstStartChoice,
    FirstStartError,
    FirstStartResult,
    FirstStartState,
    FirstStartWizard,
    wizard_from_api_bundle,
    wizard_from_memory_bundle,
    wizard_from_sqlite_bundle,
)
from nodeone.core.eposone_domain.link_en1 import (
    LABEL_LINK_EN1,
    IdMappingTable,
    LinkEn1Assistant,
    LinkEn1Error,
    LinkEn1Result,
    LinkEn1State,
    assistant_from_memory_bundles,
    build_export_envelope,
)
from nodeone.core.eposone_domain.devices import (
    DeviceRegistry,
    DeviceRegistryError,
    RegisterDeviceInput,
    new_device_id,
    registry_from_bundle,
)
from nodeone.core.eposone_domain.platform_sync import (
    PlatformSyncBridge,
    PlatformSyncError,
    SyncClientContext,
    assert_platform_sync_allowed,
    bridge_for_api_org,
    resolve_sync_context,
)
from nodeone.core.eposone_domain.ports import (
    CashShiftRepository,
    ConfigRepository,
    CustomerRepository,
    DeviceRepository,
    EmployeeRepository,
    InventoryRepository,
    OrderRepository,
    ProductRepository,
    PromotionRepository,
)

__all__ = [
    'Address',
    'Branch',
    'BusinessConfig',
    'CashShift',
    'CashShiftRepository',
    'ConfigRepository',
    'ConnectEn1Input',
    'CreateBusinessInput',
    'Customer',
    'CustomerRepository',
    'Device',
    'DeviceRegistry',
    'DeviceRegistryError',
    'DeviceRepository',
    'Employee',
    'EmployeeRepository',
    'FIRST_START_CHOICES',
    'FirstStartChoice',
    'FirstStartError',
    'FirstStartResult',
    'FirstStartState',
    'FirstStartWizard',
    'IdMappingTable',
    'InventoryBalance',
    'InventoryRepository',
    'KitLine',
    'LABEL_CONNECT_EN1',
    'LABEL_CREATE_BUSINESS',
    'LABEL_LINK_EN1',
    'LinkEn1Assistant',
    'LinkEn1Error',
    'LinkEn1Result',
    'LinkEn1State',
    'Order',
    'OrderLine',
    'OrderRepository',
    'Payment',
    'PlatformSyncBridge',
    'PlatformSyncError',
    'Product',
    'ProductRepository',
    'Promotion',
    'PromotionRepository',
    'Register',
    'RegisterDeviceInput',
    'SyncClientContext',
    'TaxRate',
    'assert_platform_sync_allowed',
    'assistant_from_memory_bundles',
    'bridge_for_api_org',
    'build_export_envelope',
    'new_device_id',
    'registry_from_bundle',
    'resolve_sync_context',
    'wizard_from_api_bundle',
    'wizard_from_memory_bundle',
    'wizard_from_sqlite_bundle',
]
