MAX_CONTENT_LEN = 2000
MIN_QR_SIZE = 80
MAX_QR_SIZE = 2000
DEFAULT_QR_SIZE = 300
ALLOWED_FORMATS = frozenset({'png', 'svg', 'pdf'})
ALLOWED_ERROR_LEVELS = frozenset({'L', 'M', 'Q', 'H'})
RATE_LIMIT_WINDOW_SEC = 60
RATE_LIMIT_MAX_REQUESTS = 40
