MAX_CONTENT_LEN = 2000
MIN_QR_SIZE = 80
MAX_QR_SIZE = 2000
DEFAULT_QR_SIZE = 300
ALLOWED_FORMATS = frozenset({'png', 'svg', 'pdf'})
ALLOWED_ERROR_LEVELS = frozenset({'L', 'M', 'Q', 'H'})
RATE_LIMIT_WINDOW_SEC = 60
RATE_LIMIT_MAX_REQUESTS = 40

# Branding (Phase 3)
DEFAULT_FILL = '#000000'
DEFAULT_BG = '#FFFFFF'
MIN_BORDER_MODULES = 1
MAX_BORDER_MODULES = 10
DEFAULT_BORDER_MODULES = 4
MAX_LOGO_BYTES = 250_000
MAX_LOGO_SIDE_PX = 512

# Lote (Fase 7)
MAX_BATCH_LINES = 40
